{{config (materialized = 'table')}}

WITH CUSTOMERORDERS AS(
select C.CustomerID,CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, count(O.OrderID) as NO_OF_ORDERS
from EMART_OMS.L1_LANDING.CUSTOMERS C
JOIN EMART_OMS.L1_LANDING.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID,CUSTOMERNAME
ORDER BY NO_OF_ORDERS DESC)

SELECT CUSTOMERID, CUSTOMERNAME, NO_OF_ORDERS
FROM CUSTOMERORDERS